Add ServalError::AnyhowError to ease conversion of, well, anyhow errors
Note that this required getting rid of the `WasmEngineError` enum variant, because `wasi_common:Error`
itself is implemented on top of `anyhow::Error`, and the compiler is insufficiently clever to handle
that case (which is fine by me).

````sh
error[E0119]: conflicting implementations of trait `std::convert::From<wasi_common::Error>` for type `errors::ServalError`
````